spring.application.name=backend
#config database
##
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/english_center
spring.datasource.username=root
spring.datasource.password=111111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
##

###
#config jwt
myapp.jwt.base64-secret=vVI0VGQbs54nKIIVGLBC1fOrEUD0y7C2Zk90uSKXUsEgFhN3LuDoJg0uECKTCvni8T00LGVh09jih+0M7dZtPg==

#expiration : 100 day
myapp.jwt.access-token-validity-in-seconds=8640000
myapp.jwt.refresh-token-validity-in-seconds=8640000
###
